### DISCUSSION TITLE
Zoom on Live Preview

### DISCUSSION THREAD

**Discussion by Paulexe** [kirby-tools/community#20] [Ideas]
My problem: When i put the Live Preview in in a 1/2 collumn it shows me the tablet version of the website. I would rather have a look at my desktop version, even if tiny / zoomed out. Is this possible?

**Comment by johannschopplich** [comment]
Yes, you can achieve such an effect with the [preview mode feature](http://localhost:3000/docs/live-preview/preview-mode) of the plugin. By default, the rendered HTML contains a `data-preview-mode` attribute on the document root tag (`<html>`), which you could use to scale the site:

```css [assets/css/main.css]
[data-preview-mode] {
  --scale-factor: 0.75;
}

body {
  transform: scale(var(--scale-factor, 1));
  transform-origin: 0 0;
  width: calc(100% / var(--scale-factor, 1));
}
```
