### DISCUSSION TITLE
Resolve text in custom block with blocks resolver

### DISCUSSION THREAD

**Discussion by alancwoo** [kirby-tools/community#26] [Q&A] [answered]
Say I have a custom block defined like:

```
fields:
  description:
    type: blocks
    fieldsets:
      - type: test-custom
           name: Test Custom
           fields:
             excerpt:
               type: textarea
```

If i want to adjust this block's output via a resolver, is it possible via:

```
// config.php
return [
    'blocksResolver' => [
        'resolvers' => [
            'test-custom:excerpt' => fn (Field $field, Block $block) => [
                // adjust output
            ]
        ]
    ]
];
```

I can't seem to catch this `block:field` output at all, although I'm able to resolve `file` fields within my custom block.

```
getkirby/cms: 4.5.0
johannschopplich/kirby-headless: 4.0.2
```
