### ISSUE TITLE
Preview not working for blocks on site

### ISSUE THREAD

**Issue by arnoson** [kirby-tools/community#22]
### Environment

- Plugin Version `1.4.0`
- Kirby Version `4.4.1`

### Reproduction

Create a site blueprint

```yaml
title: Site

columns:
  - width: 1/3
    fields:
      main:
        type: blocks

  - width: 2/3
    sticky: true
    sections:
      livePreview:
        type: preview

```

and the corresponding template:

```php
<?= $site->main()->toBlocks() ?>
```

### Describe the bug

The live preview is not working, if the blocks are defined directly on the site blueprint (as shown in Reproduction). If I define the blocks on a page like home instead of the site, everything works as expected.
