### ISSUE TITLE
`files` fields in blocks disappear after translation

### ISSUE THREAD

**Issue by AlexanderBoenninger** [kirby-tools/community#29]
### Environment

Hey. 

I have that issue, where i use the translator on a page. There is a block with a files field. 
The files field is somehow `translate: false` and not editable. When using the import or/and the translating function, the files field loses all the entries. 

### Reproduction

Block with files field
```
name: Bilder Slider
icon: images
preview: fields
wysiwyg: true

tabs:
  content:
    fields:
      entrys:
        extends: fields/img_slider
        min: 2
...
```

**fields/img_slider**
```
type: structure
label: Karussel Content
translate: false

fields:
  format:
    type: toggles
    default: "Bild"
    options:
      - Video
      - Bild
  video:
    extends: fields/video
    when:
      format: Video
  bild:
    label: Karussel Bild
    when:
      format: Bild
    type: files
    size: full
    info: "{{ file.dimensions }}"
    layout: cards
    max: 1
    templalte: casefile
    uploads: casefile
    query: site.pages.children.images
    image:
      ratio: 4/3
      back: white

```

### Describe the bug

1. I import the content on the En page. 
2. I translate the page ( Or not – turns out the import it self without translating causes the behavior as well) 
3. The files are there as expected. (not editable – but thats ok.)
4. I save the page and reload.  –> Files field is empty. And since the is no way to  edit the files field i am stuck with an empty files field.

### Additional context

:-/  Any idea? Did is use it wrong or is there a bug?

### Logs

```shell-script

```
